In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df=pd.read_csv('covid_toy.csv')

In [10]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [12]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [14]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [16]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [18]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [22]:
X_train

age  gender  fever   cough       city
31   83    Male  103.0    Mild    Kolkata
88    5  Female  100.0    Mild    Kolkata
11   65  Female   98.0    Mild     Mumbai
17   40  Female   98.0  Strong      Delhi
9    64  Female  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
99   10  Female   98.0  Strong    Kolkata
5    84  Female    NaN    Mild  Bangalore
56   71    Male    NaN  Strong    Kolkata
77    8  Female  101.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi

[80 rows x 5 columns]

# AAM ZINDAGI

In [27]:
# adding simple imputer to fever col
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])
X_train_fever.shape
X_train_fever

array([[103.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [100.74647887],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [100.74647887],
       [103.        ],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [100.        ],
       [100.74647887],
       [102.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [100.        ],
       [100.74647887],
       [103.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [103.        ],
       [104.        ],
       [102.        ],
       [103.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [100.74647887],
       [101.        ],
       [100

In [29]:
# ordinal encoding cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [41]:
# one hot encoding-> gender,city

ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape
X_train_gender_city

array([[1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],


In [43]:
# extracting age
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age

array([[83],
       [ 5],
       [65],
       [40],
       [64],
       [31],
       [75],
       [ 5],
       [16],
       [49],
       [12],
       [80],
       [11],
       [12],
       [79],
       [73],
       [15],
       [65],
       [82],
       [55],
       [34],
       [64],
       [19],
       [18],
       [27],
       [10],
       [23],
       [46],
       [47],
       [81],
       [60],
       [33],
       [70],
       [42],
       [69],
       [69],
       [47],
       [20],
       [16],
       [25],
       [23],
       [38],
       [14],
       [11],
       [24],
       [66],
       [ 5],
       [20],
       [ 6],
       [14],
       [44],
       [69],
       [24],
       [71],
       [42],
       [20],
       [81],
       [19],
       [50],
       [27],
       [83],
       [48],
       [59],
       [13],
       [49],
       [17],
       [26],
       [42],
       [49],
       [25],
       [54],
       [80],
       [34],
       [65],
       [65],
       [10],
       [84],

In [45]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformd=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
X_train_transformed

array([[ 83.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 40.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 64.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 75.        , 100.74647887,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.    

In [52]:
columns = ['age', 'fever_mild','fever_strong', 'gender_male', 'city_mumbai', 'city_bangalore', 'cough']

# Convert NumPy array to DataFrame
X_train_df = pd.DataFrame(X_train_transformed, columns=columns)
X_train_df

age  fever_mild  fever_strong  gender_male  city_mumbai  city_bangalore  \
0   83.0  103.000000           1.0          0.0          1.0             0.0   
1    5.0  100.000000           0.0          0.0          1.0             0.0   
2   65.0   98.000000           0.0          0.0          0.0             1.0   
3   40.0   98.000000           0.0          1.0          0.0             0.0   
4   64.0  101.000000           0.0          1.0          0.0             0.0   
..   ...         ...           ...          ...          ...             ...   
75  10.0   98.000000           0.0          0.0          1.0             0.0   
76  84.0  100.746479           0.0          0.0          0.0             0.0   
77  71.0  100.746479           1.0          0.0          1.0             0.0   
78   8.0  101.000000           0.0          0.0          1.0             0.0   
79  83.0   98.000000           1.0          1.0          0.0             0.0   

    cough  
0     0.0  
1     0.0  
2     0.0  
3     1.0  
4     0.0  
..    ...  
75    1.0  
76    0.0  
77    1.0  
78    0.0  
79    0.0  

[80 rows x 7 columns]

# Mentos zindagi

In [54]:
from sklearn.compose import ColumnTransformer


In [58]:
ct=ColumnTransformer(transformers=[
      ('tnf1',SimpleImputer(),['fever']),
      ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
      ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [60]:
ct.fit_transform(X_train)

array([[103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [100.74647887,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [64]:
ct.fit_transform(X_train).shape

(80, 7)

In [66]:
ct.fit_transform(X_test).shape

(20, 7)